using Domain.Enums.Reports;

namespace Domain.Entities.Reports;

public class Report
{
    public Guid Id { get; private set; }
    
    public string Name { get; private set; }
    public ReportType ReportType { get; private set; }

    // generated by
    public string UserId { get; private set; }
    
    public string? DataJson { get; private set; }
    public string? FilePath { get; private set; }
    
    public DateTime? StartDate { get; private set; }
    public DateTime? EndDate { get; private set; }
    
    public DateTime GeneratedAt { get; private set; }
    
    private Report() {}

    public static Report Create(
        string name,
        string userId,
        ReportType reportType,
        DateTime? startDate,
        DateTime? endDate,
        string dataJson)
    {
        return new Report
        {
            Id = Guid.NewGuid(),
            Name = name,
            UserId = userId,
            ReportType = reportType,
            StartDate = startDate,
            EndDate = endDate,
            DataJson = dataJson,
            GeneratedAt = DateTime.UtcNow
        };
    }
}